version: '3.4'
services:
  flask:
    build: .
    container_name: "flask-covid"
    ports:
      - 5000:5000
    labels:
      - "traefik.enable=true"
      - "traefik.backend=flask"
      - "traefik.http.routers.flask.rule=Host(`api-covid.unthinkingdepths.fr`)"

      - "traefik.http.routers.flask.entrypoints=websecure"
      - "traefik.http.routers.flask.tls=true"
      - "traefik.http.routers.flask.tls.certresolver=letsencrypt"

      - "traefik.http.routers.flask.middlewares=testheader"

    networks:
      - webflask

networks:
  webflask:
    external:
      name: web
